[versions]
agp = "8.1.2" # 7.4.1 is the maximum version supported by IDEA 2023.1
android-compile = "34"
android-min = "21"
android-target = "32"
compose = "1.5.1"
coroutines = "1.7.3"
jacoco = "0.8.7"
jvm-toolchain = "11"
kotlin = "1.9.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.7.2" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.6.2" }
androidx-test = { module = "androidx.test:core", version = "1.5.0" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.1" }
material = { module = "com.google.android.material:material", version = "1.9.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.10.3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
atomicfu = { id = "kotlinx-atomicfu", version = "0.21.0" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.0" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.16.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }
validator = { id = "binary-compatibility-validator", version = "0.13.0" }
