[versions]
agp = "7.3.1"
android-compile = "android-33"
android-target = "32"
android-min = "21"
compose = "1.2.0"
coroutines = "1.6.4"
jacoco = "0.8.7"
kotlin = "1.7.20"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.6.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.5.1" }
androidx-test = { module = "androidx.test:core", version = "1.4.0" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
material = { module = "com.google.android.material:material", version = "1.6.1" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
atomicfu = { id = "kotlinx-atomicfu", version = "0.18.2" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.20" }
java8 = { id = "net.mbonnin.one.eight", version = "0.2" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.12.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }
validator = { id = "binary-compatibility-validator", version = "0.8.0" }
