[versions]
agp = "8.3.0" # 7.4.1 is the maximum version supported by IDEA 2023.1
android-compile = "34"
android-min = "21"
android-target = "32"
compose = "1.6.1"
coroutines = "1.8.0"
jacoco = "0.8.7"
jvm-toolchain = "11"
kotlin = "1.9.23"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.2" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.7.0" }
androidx-test = { module = "androidx.test:core", version = "1.5.0" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.5.0" }
material = { module = "com.google.android.material:material", version = "1.11.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.11.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
api = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.14.0" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.2.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.27.0" }
