title: Krayon
description: Cross platform (Android, iOS & JavaScript) canvas library.

plugins:
  - jekyll-remote-theme
  - jekyll-spaceship

remote_theme: jekyll/minima

kramdown:
  parse_block_html: true

jekyll-spaceship:
  processors:
    - mermaid-processor
  mermaid-processor:
    mode: pre-fetch
    syntax:
      code: 'mermaid'
