plugins {
    id("kotlin-conventions")
    alias(libs.plugins.compose)
    alias(libs.plugins.compose.compiler)
}

@OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
kotlin {
    jvmToolchain(libs.versions.jvm.toolchain.get().toInt())

    jvm("desktop")
    wasmJs {
        outputModuleName = "documentation"
        browser {
            commonWebpackConfig {
                outputFileName = "documentation.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        commonMain.dependencies {
            implementation(compose.components.resources)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.runtime)
            implementation(compose.ui)
            implementation(libs.coroutines.core)
            implementation(libs.datetime)
            implementation(libs.highlights)
            implementation(libs.markdown.renderer.code)
            implementation(libs.markdown.renderer.m2)
            implementation(libs.navigation)
            implementation(projects.box)
            implementation(projects.compose)
        }

        getByName("desktopMain").dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.coroutines.swing)
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.juul.krayon.documentation.MainKt"
    }
}

// Kotlinter shouldn't check the sources generated by the Compose resources plugin.
tasks.withType<org.jmailen.gradle.kotlinter.tasks.LintTask>().configureEach {
    exclude { it.file.path.contains("/generated/") }
}
tasks.withType<org.jmailen.gradle.kotlinter.tasks.FormatTask>().configureEach {
    exclude { it.file.path.contains("/generated/") }
}

// Assembles the Compose resources directory by merging the static resources with a copy of the
// chart sample sources, so that the code displayed in the app is always the exact code that the
// app compiles and runs.
val syncDocumentationResources by tasks.registering(Sync::class) {
    from(layout.projectDirectory.dir("src/commonMain/composeResources"))
    from(layout.projectDirectory.dir("src/commonMain/kotlin/samples")) {
        include("**/*.kt")
        into("files/samples")
    }
    into(layout.buildDirectory.dir("generated/composeResources"))
}

compose.resources {
    packageOfResClass = "com.juul.krayon.documentation.generated.resources"
    customDirectory(
        sourceSetName = "commonMain",
        directoryProvider = layout.dir(syncDocumentationResources.map { it.destinationDir }),
    )
}
