name: GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

jobs:
  deploy:
    if: github.repository_owner == 'JuulLabs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
        id: pages
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - run: ./gradlew :documentation:jsBrowserDistribution

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/build/dist/js/productionExecutable
